############################################################
### Dataset / Eval Items
############################################################
dataset_config: datasets/adk-tools/toolbox.evalset.json
dataset_format: adk-format
setup_directory: datasets/adk-tools/setup
agent_name: myagent
agent_module: myagent